title: FileDownloads
modelClass: ChananSystems\FileDownloads\Models\FileDownload
list: $/chanansystems/filedownloads/models/filedownload/columns.yaml
recordUrl: 'chanansystems/filedownloads/filedownloads/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
